In [5]:
%pip install pandas

Collecting pandas
  Downloading pandas-2.2.3-cp311-cp311-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.23.2 (from pandas)
  Downloading numpy-2.2.1-cp311-cp311-win_amd64.whl.metadata (60 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\manan\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Downloading pytz-2024.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2024.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\manan\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-2.2.3-cp311-cp311-win_amd64.whl (11.6 MB)
   ---------------------------------------- 0.0/11.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.6 MB ? eta -:--:--
   --- ------------------------------------ 1.0/11.6 MB 4.6 MB/s eta 0:00:03
   -------- ------------------------------- 2.4/11.6 MB 5.6 MB/s eta 0:00:02
   ------------- -------------------------- 3.9/11.6 MB 6.0 MB/s eta 0:00:02
   ------------------ --------------------- 5.2/11.6 MB 6.1 MB/s eta 0:00:02
   ---------------------- ----------------- 6.6/11.6 MB 6.2 MB/s eta 0:00:01
   --------------------------- ------------ 8.1/11.6 MB 6.3 MB/s eta 0:00:01
   -------------------------------- ------- 9.4/11.6 MB 6.2 MB/s eta 0:00:01
   ------------------------------------- -- 11.0/11.6 MB 6.4 MB/s eta 0:00:01
   ---------------------------------------- 11.6/11.6 MB 6.2 MB/s eta 0:00:00
Downloading numpy-2.2.1-cp311-cp311-win_amd64.whl (12.9 MB)
   ---------------------------------------- 0.0/12.9 MB ? eta -:--:--
   ---- ----------------------------------- 1.3/12.9 MB 6.7 MB/s eta 0:00:02
   -------- ------------------------------- 2.6/12.9 MB 6.6 MB/s eta 0:00:02
   ------------ --------------------------- 4.2/12.9 MB 6.6 MB/s eta 0:00:02
   ----------------- ---------------------- 5.5/12.9 MB 6.6 MB/s eta 0:00:02
   --------------------- ------------------ 7.1/12.9 MB 6.6 MB/s eta 0:00:01
   ----------------------- ---------------- 7.6/12.9 MB 6.2 MB/s eta 0:00:01
   ---------------------------- ----------- 9.2/12.9 MB 6.2 MB/s eta 0:00:01
   ------------------------------- -------- 10.2/12.9 MB 6.1 MB/s eta 0:00:01
   ----------------------------------- ---- 11.5/12.9 MB 6.1 MB/s eta 0:00:01
   -------------------------------------- - 12.6/12.9 MB 6.1 MB/s eta 0:00:01
   ---------------------------------------- 12.9/12.9 MB 5.9 MB/s eta 0:00:00
Downloading pytz-2024.2-py2.py3-none-any.whl (508 kB)
Downloading tzdata-2024.2-py2.py3-none-any.whl (346 kB)
Installing collected packages: pytz, tzdata, numpy, pandas
Successfully installed numpy-2.2.1 pandas-2.2.3 pytz-2024.2 tzdata-2024.2
Note: you may need to restart the kernel to use updated packages.

In [6]:
import pandas as pd

In [4]:
df = pd.read_csv("apple_products.csv")

In [5]:
df.head()

,Product Name,Product URL,Brand,Sale Price,Mrp,Discount Percentage,Number Of Ratings,Number Of Reviews,Upc,Star Rating,Ram
0,"APPLE iPhone 8 Plus (Gold, 64 GB)",https://www.flipkart.com/apple-iphone-8-plus-g...,Apple,49900,49900,0,3431,356,MOBEXRGV7EHHTGUH,4.6,2 GB
1,"APPLE iPhone 8 Plus (Space Grey, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,0,3431,356,MOBEXRGVAC6TJT4F,4.6,2 GB
2,"APPLE iPhone 8 Plus (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,0,3431,356,MOBEXRGVGETABXWZ,4.6,2 GB
3,"APPLE iPhone 8 (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-silver...,Apple,77000,77000,0,11202,794,MOBEXRGVMZWUHCBA,4.5,2 GB
4,"APPLE iPhone 8 (Gold, 256 GB)",https://www.flipkart.com/apple-iphone-8-gold-2...,Apple,77000,77000,0,11202,794,MOBEXRGVPK7PFEJZ,4.5,2 GB

In [6]:
df.count()

Product Name           62
Product URL            62
Brand                  62
Sale Price             62
Mrp                    62
Discount Percentage    62
Number Of Ratings      62
Number Of Reviews      62
Upc                    62
Star Rating            62
Ram                    62
dtype: int64

In [7]:
df['Mrp'].max()

np.int64(149900)

In [12]:
df[df['Sale Price']==140900]

,Product Name,Product URL,Brand,Sale Price,Mrp,Discount Percentage,Number Of Ratings,Number Of Reviews,Upc,Star Rating,Ram
24,"APPLE iPhone 12 Pro (Silver, 512 GB)",https://www.flipkart.com/apple-iphone-12-pro-s...,Apple,140900,149900,6,542,42,MOBFWBYZ5UY6ZBVA,4.5,4 GB
41,"APPLE iPhone 12 Pro (Pacific Blue, 512 GB)",https://www.flipkart.com/apple-iphone-12-pro-p...,Apple,140900,149900,6,545,42,MOBFWBYZTHSXKMGW,4.5,4 GB

In [15]:
type(df['Product Name'] )

pandas.core.series.Series

In [17]:
list(df['Product Name'])[0]

'APPLE iPhone 8 Plus (Gold, 64 GB)'

In [42]:
# produst_name= list(df['Product Name'])[0]
# for i in range(len(produst_name)):
#     print(produst_name[i][0:15].strip())
#strip for remove white space from string

list(df['Product Name'])[0][0:15].strip()

'APPLE iPhone 8'

In [43]:
#making new column for this
df['new_column'] = df['Product Name'].str[0:15]

In [44]:
df.head()

,Product Name,Product URL,Brand,Sale Price,Mrp,Discount Percentage,Number Of Ratings,Number Of Reviews,Upc,Star Rating,Ram,new_column
0,"APPLE iPhone 8 Plus (Gold, 64 GB)",https://www.flipkart.com/apple-iphone-8-plus-g...,Apple,49900,49900,0,3431,356,MOBEXRGV7EHHTGUH,4.6,2 GB,APPLE iPhone 8
1,"APPLE iPhone 8 Plus (Space Grey, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,0,3431,356,MOBEXRGVAC6TJT4F,4.6,2 GB,APPLE iPhone 8
2,"APPLE iPhone 8 Plus (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-plus-s...,Apple,84900,84900,0,3431,356,MOBEXRGVGETABXWZ,4.6,2 GB,APPLE iPhone 8
3,"APPLE iPhone 8 (Silver, 256 GB)",https://www.flipkart.com/apple-iphone-8-silver...,Apple,77000,77000,0,11202,794,MOBEXRGVMZWUHCBA,4.5,2 GB,APPLE iPhone 8
4,"APPLE iPhone 8 (Gold, 256 GB)",https://www.flipkart.com/apple-iphone-8-gold-2...,Apple,77000,77000,0,11202,794,MOBEXRGVPK7PFEJZ,4.5,2 GB,APPLE iPhone 8

In [ ]:
df.sort_values(by=['Star Rating'], ascending=False)

,Product Name,Product URL,Brand,Sale Price,Mrp,Discount Percentage,Number Of Ratings,Number Of Reviews,Upc,Star Rating,Ram,new_column
15,"APPLE iPhone 11 Pro Max (Gold, 64 GB)",https://www.flipkart.com/apple-iphone-11-pro-m...,Apple,117100,117100,0,1078,101,MOBFKCTSAPAYNSGG,4.7,4 GB,APPLE iPhone 11
20,"APPLE iPhone 11 Pro Max (Midnight Green, 64 GB)",https://www.flipkart.com/apple-iphone-11-pro-m...,Apple,117100,117100,0,1078,101,MOBFKCTSRYPAQNYT,4.7,4 GB,APPLE iPhone 11
17,"APPLE iPhone 11 Pro Max (Space Grey, 64 GB)",https://www.flipkart.com/apple-iphone-11-pro-m...,Apple,117100,117100,0,1078,101,MOBFKCTSKDMKCGQS,4.7,4 GB,APPLE iPhone 11
16,"APPLE iPhone 11 Pro Max (Midnight Green, 256 GB)",https://www.flipkart.com/apple-iphone-11-pro-m...,Apple,131900,131900,0,1078,101,MOBFKCTSCAAKGQV7,4.7,4 GB,APPLE iPhone 11
14,"APPLE iPhone 11 Pro Max (Gold, 256 GB)",https://www.flipkart.com/apple-iphone-11-pro-m...,Apple,131900,131900,0,1078,101,MOBFKCTS7HCHSPFH,4.7,4 GB,APPLE iPhone 11
...,...,...,...,...,...,...,...,...,...,...,...,...
52,"APPLE iPhone SE (White, 64 GB)",https://www.flipkart.com/apple-iphone-se-white...,Apple,29999,39900,24,95807,8154,MOBFWQ6BGWDVGF3E,4.5,2 GB,APPLE iPhone SE
53,"APPLE iPhone SE (Black, 128 GB)",https://www.flipkart.com/apple-iphone-se-black...,Apple,34999,44900,22,95909,8161,MOBFWQ6BHUEVZPXD,4.5,2 GB,APPLE iPhone SE
57,"APPLE iPhone SE (Black, 64 GB)",https://www.flipkart.com/apple-iphone-se-black...,Apple,29999,39900,24,95909,8161,MOBFWQ6BR3MK7AUG,4.5,4 GB,APPLE iPhone SE
54,"APPLE iPhone SE (White, 128 GB)",https://www.flipkart.com/apple-iphone-se-white...,Apple,34999,44900,22,95807,8154,MOBFWQ6BJEHMUUZY,4.5,2 GB,APPLE iPhone SE
55,"APPLE iPhone SE (Red, 128 GB)",https://www.flipkart.com/apple-iphone-se-red-1...,Apple,34999,44900,22,95909,8161,MOBFWQ6BJTVFKPEJ,4.5,2 GB,APPLE iPhone SE